<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-NM6NUFVG" failures="1" tests="4" name="com.mycompany.app.HardAndSoftAssert" time="14.792" errors="0" timestamp="2022-04-21T18:19:54 IST" skipped="0">
  <testcase classname="com.mycompany.app.HardAndSoftAssert" name="starting_point" time="14.431"/>
  <system-out>
    <![CDATA[starting_point Method is executed]]>
  </system-out>
  <testcase classname="com.mycompany.app.HardAndSoftAssert" name="checkTitle" time="0.032">
    <failure message="The following asserts failed:
	expected [Kite - Zerodha&#039;s fast and elegant flagship trading platform] but found [Kite - Zerodha&#039;s fast and elegant flagship trading jlatform]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Kite - Zerodha's fast and elegant flagship trading platform] but found [Kite - Zerodha's fast and elegant flagship trading jlatform]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.mycompany.app.HardAndSoftAssert.checkTitle(HardAndSoftAssert.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- checkTitle -->
  <system-out>
    <![CDATA[checkTitle method is executed]]>
  </system-out>
  <testcase classname="com.mycompany.app.HardAndSoftAssert" name="LoginTest" time="0.237"/>
  <system-out>
    <![CDATA[LoginTest method is executed]]>
  </system-out>
  <testcase classname="com.mycompany.app.HardAndSoftAssert" name="ClickElement" time="0.092"/>
  <system-out>
    <![CDATA[ClickElement method is executed]]>
  </system-out>
</testsuite> <!-- com.mycompany.app.HardAndSoftAssert -->
